# Generated by Django 5.2.8 on 2025-11-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="easiness_factor",
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="interval",
            field=models.IntegerField(default=0),
        ),
    ]
