# Generated by Django 5.2.8 on 2025-11-21 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_userprogress_easiness_factor_userprogress_interval"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabulary",
            name="antonyms",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="synonyms",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="tags",
            field=models.ManyToManyField(blank=True, to="api.tag"),
        ),
    ]
