# Generated by Django 5.2.8 on 2025-11-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_vocabulary_antonyms_vocabulary_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabulary",
            name="related_words",
            field=models.ManyToManyField(blank=True, to="api.vocabulary"),
        ),
    ]
