# Generated by Django 5.2.8 on 2025-11-21 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="elevenlabs_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="GrammarTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "A1 - Beginner"),
                            ("A2", "A2 - Elementary"),
                            ("B1", "B1 - Intermediate"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("articles", "Articles"),
                            ("plurals", "Plurals"),
                            ("verbs", "Verb Conjugation"),
                            ("separable_verbs", "Separable Verbs"),
                            ("modal_verbs", "Modal Verbs"),
                            ("cases", "Cases (Nominativ, Akkusativ, Dativ)"),
                            ("prepositions", "Prepositions"),
                            ("sentence_structure", "Sentence Structure"),
                            ("word_order", "Word Order"),
                            ("time_expressions", "Time Expressions"),
                            ("adjective_endings", "Adjective Endings"),
                            ("comparatives", "Comparatives & Superlatives"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("examples", models.JSONField(blank=True, default=list)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["level", "order", "category"],
                "unique_together": {("level", "category", "title")},
            },
        ),
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text_content", models.TextField()),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="podcasts/"),
                ),
                ("voice_id", models.CharField(default="default", max_length=100)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
