# Generated by Django 5.2.8 on 2025-11-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_userprofile_elevenlabs_api_key_grammartopic_podcast"),
    ]

    operations = [
        migrations.AddField(
            model_name="grammartopic",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("ar", "Arabic"),
                    ("ru", "Russian"),
                ],
                default="de",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="vocabulary",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("ar", "Arabic"),
                    ("ru", "Russian"),
                ],
                default="de",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="type",
            field=models.CharField(
                choices=[
                    ("verb", "Verb"),
                    ("noun", "Noun"),
                    ("phrase", "Phrase"),
                    ("connector", "Connector"),
                    ("adjective", "Adjective"),
                    ("adjective", "Adjective"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
