# Generated by Django 5.2.8 on 2025-11-22 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_grammartopic_language_vocabulary_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grammartopic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='next_review_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('ar', 'Arabic'), ('ru', 'Russian')], db_index=True, default='de', max_length=2),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='grammartopic',
            unique_together={('level', 'category', 'title', 'created_by')},
        ),
    ]
