# Generated by Django 5.2.8 on 2025-11-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_grammartopic_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='elevenlabs_api_key',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_tts_api_key',
            field=models.CharField(blank=True, default='', help_text='Google Cloud API Key for Text-to-Speech', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_tts_language',
            field=models.CharField(blank=True, default='de-DE', help_text='Preferred TTS language code', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_tts_voice',
            field=models.CharField(blank=True, default='de-DE-Wavenet-F', help_text='Preferred Google TTS voice name', max_length=100),
        ),
    ]
