# Generated by Django 5.2.8 on 2025-11-22 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_userprofile_elevenlabs_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='related_concepts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('ar', 'Arabic'), ('ru', 'Russian')], default='de', max_length=2)),
                ('topic', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=50)),
                ('questions', models.JSONField(default=list)),
                ('user_answers', models.JSONField(default=dict)),
                ('feedback', models.JSONField(default=dict)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
