# Generated by Django 5.2.8 on 2025-11-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_vocabulary_related_concepts_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deepgram_api_key',
            field=models.CharField(blank=True, default='', help_text='Deepgram API Key for Text-to-Speech', max_length=500),
        ),
    ]
