# Generated by Django 5.2.8 on 2025-11-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile_deepgram_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='speechify_api_key',
            field=models.CharField(blank=True, default='', help_text='Speechify API Key for Text-to-Speech', max_length=500),
        ),
    ]
