# Generated by Django 5.2.8 on 2025-11-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userprofile_speechify_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='last_practiced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='total_practice_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='wrong_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='type',
            field=models.CharField(choices=[('noun', 'Nomen (or Substantiv / Hauptwort)'), ('verb', 'Verb (or Zeitwort / Tätigkeitswort)'), ('adjective', 'Adjective (or Eigenschaftswort)'), ('article', 'Artikel (or Begleiter / Geschlechtswort)'), ('pronoun', 'Pronomen (or Fürwort)'), ('numeral', 'Numerale (or Zahlwort)'), ('adverb', 'Adverb (or Umstandswort)'), ('preposition', 'Präposition (or Verhältniswort)'), ('conjunction', 'Konjunktion (or Bindewort)'), ('interjection', 'Interjektion (or Ausrufewort)'), ('phrase', 'Phrase'), ('other', 'Other')], max_length=20),
        ),
    ]
