# Generated by Django 5.2.8 on 2025-11-23 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_userprofile_is_email_verified_userprofile_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='score',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='user_answers',
        ),
        migrations.AddField(
            model_name='exam',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='best_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answers', models.JSONField(default=dict)),
                ('feedback', models.JSONField(default=dict)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.exam')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
