# Generated by Django 5.2.8 on 2025-11-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_exam_options_remove_exam_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='embedding',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
