# Generated by Django 5.2.8 on 2025-11-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_vocabulary_embedding_savedtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', help_text='Gemini API Key', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openrouter_api_key',
            field=models.CharField(blank=True, default='', help_text='OpenRouter API Key', max_length=500),
        ),
    ]
