# Generated by Django 5.2.8 on 2025-11-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_performance_indexes'),
        ('api', '0019_userprofile_gemini_api_key_and_more'),
    ]

    operations = [
    ]
