# Generated by Django 5.2.8 on 2025-11-25 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_20251125_1337'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('story', 'Story'), ('article', 'Article'), ('dialogue', 'Dialogue')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficiency')], max_length=2)),
                ('target_language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('ar', 'Arabic'), ('ru', 'Russian')], max_length=2)),
                ('content_data', models.JSONField(help_text='Stores events/paragraphs/messages structure')),
                ('total_words', models.IntegerField(default=0)),
                ('vocabulary_used', models.JSONField(default=list, help_text='List of vocabulary words used')),
                ('grammar_used', models.JSONField(default=list, help_text='List of grammar points used')),
                ('is_favorite', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_tag_per_user',
        ),
        migrations.RemoveIndex(
            model_name='exam',
            name='api_exam_is_public_idx',
        ),
        migrations.RemoveIndex(
            model_name='exam',
            name='api_exam_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='grammartopic',
            name='api_grammar_level_idx',
        ),
        migrations.RemoveIndex(
            model_name='grammartopic',
            name='api_grammar_category_idx',
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='api_quiz_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='api_quiz_timestamp_idx',
        ),
        migrations.RemoveIndex(
            model_name='vocabulary',
            name='api_vocab_is_public_idx',
        ),
        migrations.RemoveIndex(
            model_name='vocabulary',
            name='api_vocab_created_at_idx',
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='generatedcontent',
            index=models.Index(fields=['user', '-created_at'], name='api_generat_user_id_21839c_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcontent',
            index=models.Index(fields=['user', 'content_type'], name='api_generat_user_id_8136e1_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedcontent',
            index=models.Index(fields=['user', 'is_favorite'], name='api_generat_user_id_66f77c_idx'),
        ),
    ]
