# Generated by Django 5.2.8 on 2025-11-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_generatedcontent_remove_tag_unique_tag_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammartopic',
            name='estimated_read_time',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='generated_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='mermaid_diagrams_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='related_topics',
            field=models.ManyToManyField(blank=True, to='api.grammartopic'),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
