# Generated by Django 5.2.8 on 2025-11-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_grammartopic_estimated_read_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcontent',
            name='generation_time_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='has_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='image_generation_status',
            field=models.CharField(choices=[('none', 'No Images'), ('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('partial', 'Partially Completed'), ('failed', 'Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='image_providers_used',
            field=models.JSONField(default=list, help_text='List of providers used for images'),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='images_generated_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='total_images_count',
            field=models.IntegerField(default=0),
        ),
    ]
