# Generated by Django 5.2.8 on 2025-11-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_generatedcontent_generation_time_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='huggingface_api_token',
            field=models.CharField(blank=True, default='', help_text='Hugging Face API Token', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stable_horde_api_key',
            field=models.CharField(blank=True, default='', help_text='Stable Horde API Key', max_length=500),
        ),
    ]
