# Generated by Django 5.2.8 on 2025-11-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_systemmetrics_adminauditlog_adminrole_apiusagelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrole',
            name='custom_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
