# Generated by Django 5.2.8 on 2025-12-06 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_adminrole_custom_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('daily_reminder', 'Daily Reminder'), ('streak_warning', 'Streak Warning'), ('new_content', 'New Content'), ('practice_reminder', 'Practice Reminder'), ('achievement', 'Achievement'), ('custom', 'Custom')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('clicked', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_reminder', models.BooleanField(default=True)),
                ('streak_warning', models.BooleanField(default=True)),
                ('new_content', models.BooleanField(default=True)),
                ('practice_reminder', models.BooleanField(default=True)),
                ('achievement', models.BooleanField(default=True)),
                ('reminder_hour', models.IntegerField(default=9)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('quiet_start', models.IntegerField(default=22)),
                ('quiet_end', models.IntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh_key', models.CharField(max_length=500)),
                ('auth_key', models.CharField(max_length=500)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Vocabulary'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ocrspace_api_key',
            field=models.CharField(blank=True, default='', help_text='OCR.space API Key for image text extraction', max_length=500),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'next_review_date'], name='api_userpro_user_id_84b426_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', '-last_seen'], name='api_userpro_user_id_4fea0a_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['created_by', 'language'], name='api_vocabul_created_aa9f48_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['created_by', '-created_at'], name='api_vocabul_created_820880_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['created_by', 'type'], name='api_vocabul_created_1b00de_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['created_by', 'last_practiced_at'], name='api_vocabul_created_67855d_idx'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', '-sent_at'], name='api_notific_user_id_17992a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification_type', '-sent_at'], name='api_notific_notific_31d3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['user', 'is_active'], name='api_pushsub_user_id_d8439a_idx'),
        ),
    ]
