# Generated by Django 5.2.8 on 2025-12-12 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_ocrspace_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='native_language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('ar', 'Arabic'), ('ru', 'Russian')], default='en', help_text='Translation language for exam questions', max_length=2),
        ),
        migrations.AddField(
            model_name='generatedcontent',
            name='native_language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('ar', 'Arabic'), ('ru', 'Russian')], default='en', help_text='Translation language for content', max_length=2),
        ),
        migrations.AddField(
            model_name='grammartopic',
            name='native_language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('ar', 'Arabic'), ('ru', 'Russian')], default='en', help_text='Translation language for examples', max_length=2),
        ),
        migrations.AddField(
            model_name='savedtext',
            name='native_language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('ar', 'Arabic'), ('ru', 'Russian')], default='en', help_text='User native language context', max_length=2),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='native_language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('ar', 'Arabic'), ('ru', 'Russian')], db_index=True, default='en', help_text='User native language for translation context', max_length=2),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['created_by', 'language', 'native_language'], name='api_vocabul_created_0db56c_idx'),
        ),
    ]
