# Generated by Django 5.2.8 on 2025-12-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_populate_native_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gemini_api_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='google_tts_api_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='huggingface_api_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='openrouter_api_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_tts_language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_tts_voice',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='speechify_api_key',
        ),
    ]
