# Generated by Django 5.2.8 on 2025-12-15 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_exam_status_userprofile_allow_notifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='episode_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='podcast',
            name='summary',
            field=models.TextField(blank=True, help_text='Summary for AI context of next episode'),
        ),
        migrations.CreateModel(
            name='PodcastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('style', models.CharField(default='Conversational', max_length=100)),
                ('tone', models.CharField(default='Casual', max_length=100)),
                ('target_audience', models.CharField(default='Beginner', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='podcast',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='api.podcastcategory'),
        ),
    ]
