# Generated by Django 5.2.8 on 2025-12-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_podcast_episode_number_podcast_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastcategory',
            name='audio_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Voice and SFX preferences'),
        ),
        migrations.AddField(
            model_name='podcastcategory',
            name='series_bible',
            field=models.JSONField(blank=True, default=dict, help_text='Stores series history and context'),
        ),
    ]
