# Generated by Django 5.2.8 on 2025-12-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_podcastcategory_audio_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='current_message',
            field=models.CharField(default='Initializing...', max_length=200),
        ),
        migrations.AddField(
            model_name='podcast',
            name='estimated_remaining',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='podcast',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='podcast',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
