# Generated by Django 5.2.8 on 2025-12-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_podcast_current_message_podcast_estimated_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='speechify_api_key',
            field=models.CharField(blank=True, default='', help_text='Speechify API Key for Text-to-Speech', max_length=500),
        ),
    ]
