# Generated by Django 5.2.8 on 2025-12-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_userprofile_speechify_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='speech_marks',
            field=models.JSONField(blank=True, default=list, help_text='Timestamped lyrics/transcript'),
        ),
    ]
