# Generated by Django 5.2.8 on 2025-12-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_podcast_speech_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Profile picture URL from social providers', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='firebase_uid',
            field=models.CharField(blank=True, help_text='Firebase User ID', max_length=128, null=True, unique=True),
        ),
    ]
