# Generated by Django 5.2.8 on 2025-12-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_firebase_auth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='speechify_api_key_2',
            field=models.CharField(blank=True, default='', help_text='Secondary Speechify API Key', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='speechify_api_key_3',
            field=models.CharField(blank=True, default='', help_text='Tertiary Speechify API Key', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='speechify_api_key_4',
            field=models.CharField(blank=True, default='', help_text='Quaternary Speechify API Key', max_length=500),
        ),
    ]
