# Generated by Django 5.2.8 on 2025-12-20 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_userprofile_speechify_api_key_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPodcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('feed_url', models.URLField(max_length=500, unique=True)),
                ('artwork_url', models.URLField(blank=True, max_length=500)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('level', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Mastery')], db_index=True, default='B1', max_length=2)),
                ('language', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('ar', 'Arabic'), ('ru', 'Russian'), ('fr', 'French'), ('es', 'Spanish')], db_index=True, default='de', max_length=2)),
                ('episode_count', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('itunes_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('podcastindex_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External Podcast',
                'verbose_name_plural': 'External Podcasts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['language', 'level'], name='api_externa_languag_0c09bc_idx'), models.Index(fields=['is_active', 'is_featured'], name='api_externa_is_acti_cbb257_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExternalEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=500, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('audio_url', models.URLField(max_length=1000)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('published_at', models.DateTimeField(db_index=True)),
                ('file_size', models.BigIntegerField(default=0, help_text='Size in bytes')),
                ('transcript', models.TextField(blank=True)),
                ('transcript_source', models.CharField(blank=True, choices=[('rss', 'RSS'), ('whisper', 'Whisper AI'), ('manual', 'Manual')], max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('listen_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='api.externalpodcast')),
            ],
            options={
                'verbose_name': 'External Episode',
                'verbose_name_plural': 'External Episodes',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalPodcastSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_position', models.PositiveIntegerField(default=0, help_text='Playback position in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_played_episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.externalepisode')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.externalpodcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_podcast_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Podcast Subscription',
                'verbose_name_plural': 'Podcast Subscriptions',
            },
        ),
        migrations.AddIndex(
            model_name='externalepisode',
            index=models.Index(fields=['podcast', '-published_at'], name='api_externa_podcast_097559_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='externalpodcastsubscription',
            unique_together={('user', 'podcast')},
        ),
    ]
