# Generated by Django 5.2.8 on 2025-12-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_external_podcast_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalepisode',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
