# Generated by Django 5.2.8 on 2025-12-20 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_external_podcast_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEpisodeInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.externalepisode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_saved'], name='api_externa_user_id_68514b_idx'), models.Index(fields=['user', 'is_liked'], name='api_externa_user_id_b390b3_idx')],
                'unique_together': {('user', 'episode')},
            },
        ),
    ]
