# Generated by Django 5.2.8 on 2025-12-20 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_assignment_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('practice_start', 'Practice Started'), ('practice_end', 'Practice Ended'), ('word_correct', 'Word Correct'), ('word_incorrect', 'Word Incorrect'), ('exam_answer', 'Exam Answer'), ('content_view', 'Content Viewed'), ('content_complete', 'Content Completed'), ('assignment_submit', 'Assignment Submitted')], max_length=30)),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.classroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'event_type', 'created_at'], name='api_learnin_user_id_703ff9_idx')],
            },
        ),
    ]
