# Generated by Django 5.2.8 on 2025-12-20 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_learningevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('listening', 'Listening'), ('reading', 'Reading'), ('speaking', 'Speaking')], max_length=20)),
                ('level', models.CharField(blank=True, max_length=5)),
                ('description', models.TextField(blank=True)),
                ('default_p_slip', models.FloatField(default=0.1)),
                ('default_p_guess', models.FloatField(default=0.2)),
                ('default_p_transit', models.FloatField(default=0.1)),
            ],
        ),
        migrations.CreateModel(
            name='SkillMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_probability', models.FloatField(default=0.3)),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('last_practiced', models.DateTimeField(null=True)),
                ('history', models.JSONField(blank=True, default=list)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_masteries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'mastery_probability'], name='api_skillma_user_id_a2e634_idx')],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
