# Generated by Django 5.2.8 on 2025-12-20 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_skill_skillmastery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(max_length=10)),
                ('language', models.CharField(default='de', max_length=2)),
                ('estimated_hours', models.FloatField(default=10)),
                ('is_published', models.BooleanField(default=False)),
                ('is_sequential', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='api.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PathEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.classroom')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.learningpath')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('path', 'student')},
            },
        ),
        migrations.CreateModel(
            name='PathNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('node_type', models.CharField(choices=[('lesson', 'Lesson'), ('exercise', 'Exercise'), ('exam', 'Exam'), ('checkpoint', 'Checkpoint')], max_length=20)),
                ('content_type', models.CharField(max_length=30)),
                ('content_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.IntegerField(default=15)),
                ('pass_threshold', models.IntegerField(default=70)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.learningpath')),
            ],
            options={
                'ordering': ['path', 'order'],
                'unique_together': {('path', 'order')},
            },
        ),
        migrations.CreateModel(
            name='NodeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='locked', max_length=20)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('score', models.FloatField(null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.pathenrollment')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pathnode')),
            ],
            options={
                'unique_together': {('enrollment', 'node')},
            },
        ),
    ]
