# Generated by Django 5.2.8 on 2025-12-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_organization_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('daily_reminder', 'Daily Reminder'), ('streak_warning', 'Streak Warning'), ('new_content', 'New Content'), ('practice_reminder', 'Practice Reminder'), ('achievement', 'Achievement'), ('custom', 'Custom'), ('assignment_new', 'New Assignment'), ('assignment_due', 'Assignment Due Soon'), ('assignment_graded', 'Assignment Graded'), ('session_reminder', 'Session Reminder'), ('session_starting', 'Session Starting'), ('join_approved', 'Join Approved'), ('streak_risk', 'Streak at Risk')], max_length=30),
        ),
    ]
