# Generated by Django 5.2.8 on 2025-12-21 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_classroom_notification_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='linked_path_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='api.pathnode'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Settings: timer, match_mode, pass_score, etc.'),
        ),
        migrations.AddField(
            model_name='assignmentprogress',
            name='linked_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.exam'),
        ),
        migrations.AddField(
            model_name='assignmentprogress',
            name='progress_data',
            field=models.JSONField(blank=True, default=dict, help_text='Type-specific progress'),
        ),
        migrations.AddField(
            model_name='assignmentprogress',
            name='time_spent',
            field=models.IntegerField(default=0, help_text='Time spent in seconds'),
        ),
        migrations.AddField(
            model_name='exam',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='api.exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Is this a master exam template?'),
        ),
    ]
