# Generated by Django 5.2.8 on 2025-12-21 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_assignment_linked_path_node_assignment_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('prompt_text', models.TextField(help_text='The detailed question or prompt for the student.')),
                ('min_words', models.IntegerField(default=100)),
                ('time_limit', models.IntegerField(default=0, help_text='Time limit in seconds (0 = no limit)')),
                ('rubric', models.JSONField(blank=True, default=dict, help_text='Grading criteria and scoring weights')),
                ('ai_grading_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='content_type',
            field=models.CharField(choices=[('exam', 'Exam'), ('story', 'Story'), ('article', 'Article'), ('grammar', 'Grammar'), ('vocab_list', 'Vocab'), ('podcast', 'Podcast'), ('writing', 'Writing')], max_length=20),
        ),
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text="The student's written text.")),
                ('word_count', models.IntegerField(default=0)),
                ('teacher_grade', models.FloatField(blank=True, null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('ai_feedback', models.JSONField(blank=True, default=dict, help_text='Structured feedback from AI (grammar, coherence)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.writingexercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignmentprogress',
            name='linked_writing_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.writingsubmission'),
        ),
    ]
