# Generated by Django 5.2.8 on 2025-12-21 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_writingexercise_alter_assignment_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('velocity', 'Velocity - Speed Matching'), ('streamline', 'Streamline - Sentence Order'), ('faceoff', 'Face-Off - 1v1 True/False'), ('synergy', 'Synergy - Team Quiz'), ('discovery', 'Discovery - Cloze/Decrypt')], default='velocity', max_length=20)),
                ('content_source', models.CharField(choices=[('exam', 'From Exam Template'), ('vocab_list', 'From Vocabulary List'), ('custom', 'Custom Questions')], default='exam', max_length=50)),
                ('content_id', models.IntegerField(blank=True, help_text='ID of exam/vocab list if using existing content', null=True)),
                ('custom_questions', models.JSONField(blank=True, default=list, help_text="Custom questions if content_source='custom'")),
                ('stages', models.JSONField(blank=True, default=list, help_text='[{mode, time_limit, question_count}]')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='{shuffle, show_answers, power_ups, team_size}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_path_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pathnode')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_configs', to='api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Players'), ('active', 'Game in Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('current_stage', models.IntegerField(default=0, help_text='Index into config.stages')),
                ('participants', models.JSONField(default=list, help_text='[{user_id, username, avatar, score, is_ready, last_seen}]')),
                ('state', models.JSONField(default=dict, help_text='Current game state (questions, timer, answers, etc.)')),
                ('join_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='api.classroom')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gameconfig')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0, help_text='Average time to answer in seconds')),
                ('is_ready', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('power_ups_used', models.JSONField(blank=True, default=list)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_records', to='api.gamesession')),
            ],
            options={
                'unique_together': {('session', 'user')},
            },
        ),
    ]
