# Generated by Django 5.2.8 on 2025-12-21 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_game_arena'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='linked_path_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pathnode'),
        ),
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('resume_link', models.URLField(help_text='Link to CV/Resume (Google Drive, LinkedIn, etc.)', max_length=500)),
                ('intro_video_link', models.URLField(help_text='Link to introduction video', max_length=500)),
                ('experience_years', models.IntegerField(default=0)),
                ('teaching_languages', models.JSONField(default=list, help_text='List of languages you can teach')),
                ('bio', models.TextField(help_text='Why do you want to teach here?')),
                ('admin_feedback', models.TextField(blank=True, help_text='Reason for rejection or internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
