# Generated by Django 5.2.8 on 2025-12-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_livesession_linked_path_node_teacherapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='content_type',
            field=models.CharField(choices=[('exam', 'Exam'), ('story', 'Story'), ('article', 'Article'), ('grammar', 'Grammar'), ('vocab_list', 'Vocab'), ('podcast', 'Podcast'), ('writing', 'Writing'), ('path', 'Learning Path')], max_length=20),
        ),
    ]
