# Generated by Django 5.2.8 on 2025-12-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_assignment_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathnode',
            name='objectives',
            field=models.JSONField(blank=True, default=list, help_text='List of learning goals'),
        ),
        migrations.AddField(
            model_name='pathnode',
            name='resources',
            field=models.JSONField(blank=True, default=list, help_text='[{title, url, type, is_teacher_only}]'),
        ),
        migrations.AddField(
            model_name='pathnode',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='path_nodes', to='api.skill'),
        ),
        migrations.AddField(
            model_name='pathnode',
            name='student_summary',
            field=models.TextField(blank=True, help_text='Mission Briefing for students'),
        ),
        migrations.AddField(
            model_name='pathnode',
            name='teacher_guide',
            field=models.TextField(blank=True, help_text='Private instructions for the teacher'),
        ),
    ]
