# Generated by Django 5.2.8 on 2025-12-22 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_path_node_materials'),
    ]

    operations = [
        # 1. ADD NEW FIELDS FIRST
        migrations.AddField(
            model_name='classroom',
            name='speaking_language',
            field=models.CharField(default='en', help_text="Students' native language", max_length=10),
        ),
        migrations.AddField(
            model_name='classroom',
            name='target_language',
            field=models.CharField(default='de', help_text='Language being taught', max_length=10),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='speaking_language',
            field=models.CharField(default='en', help_text="Student's native language (ISO code)", max_length=10),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='target_language',
            field=models.CharField(default='de', help_text='Language being learned (ISO code)', max_length=10),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # 2. CREATE NEW MODELS
        migrations.CreateModel(
            name='PathSubLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_code', models.CharField(choices=[('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Mastery')], max_length=5)),
                ('sublevel_code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('estimated_hours', models.FloatField(default=10)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublevels', to='api.learningpath')),
            ],
            options={
                'ordering': ['path', 'order'],
                'unique_together': {('path', 'sublevel_code')},
            },
        ),

        # 3. ALTER EXISTING FIELDS
        migrations.AlterField(
            model_name='learningpath',
            name='estimated_hours',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='pathnode',
            name='content_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathnode',
            name='content_type',
            field=models.CharField(blank=True, max_length=30),
        ),

        # 4. ADD LINKING FIELDS
        migrations.AddField(
            model_name='classroom',
            name='current_sublevel',
            field=models.ForeignKey(blank=True, help_text='Current sublevel (e.g., A1.1) - determines what content students see', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='api.pathsublevel'),
        ),
        migrations.AddField(
            model_name='pathnode',
            name='sublevel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.pathsublevel'),
            preserve_default=False,
        ),

        # 5. ALTER OPTIONS AND UNIQUE TOGETHER (Now that fields exist)
        migrations.AlterModelOptions(
            name='learningpath',
            options={'ordering': ['speaking_language', 'target_language']},
        ),
        migrations.AlterUniqueTogether(
            name='pathnode',
            unique_together=set(),
        ),
        migrations.AlterModelOptions(
            name='pathnode',
            options={'ordering': ['sublevel', 'order']},
        ),
        migrations.AlterUniqueTogether(
            name='learningpath',
            unique_together={('speaking_language', 'target_language')},
        ),
        migrations.AlterUniqueTogether(
            name='pathnode',
            unique_together={('sublevel', 'order')},
        ),

        # 6. REMOVE OLD FIELDS
        migrations.RemoveField(
            model_name='classroom',
            name='language',
        ),
        migrations.RemoveField(
            model_name='learningpath',
            name='is_sequential',
        ),
        migrations.RemoveField(
            model_name='learningpath',
            name='language',
        ),
        migrations.RemoveField(
            model_name='learningpath',
            name='level',
        ),
        migrations.RemoveField(
            model_name='learningpath',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='pathnode',
            name='path',
        ),
    ]
