# Generated by Django 5.2.8 on 2025-12-23 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_learning_path_v2_sublevel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='linked_path',
            field=models.ForeignKey(blank=True, help_text='The learning path this classroom follows (all students share progress)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_classrooms', to='api.learningpath'),
        ),
        migrations.CreateModel(
            name='ClassPathProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percent', models.IntegerField(default=0, help_text='0-100, class-wide completion')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_progress', to='api.classroom')),
                ('last_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.assignment')),
                ('last_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.livesession')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_progress', to='api.pathnode')),
            ],
            options={
                'verbose_name': 'Class Path Progress',
                'verbose_name_plural': 'Class Path Progress',
                'ordering': ['node__sublevel', 'node__order'],
                'unique_together': {('classroom', 'node')},
            },
        ),
        migrations.CreateModel(
            name='StudentRemediation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('missed_session', 'Missed Live Session'), ('failed_assignment', 'Failed Assignment'), ('absent', 'Absent/Inactive')], max_length=30)),
                ('remediation_type', models.CharField(choices=[('watch_recording', 'Watch Session Recording'), ('take_test', 'Take Makeup Test'), ('extra_assignment', 'Complete Extra Assignment')], default='watch_recording', max_length=30)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediations', to='api.classroom')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediations', to='api.pathnode')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'classroom', 'node')},
            },
        ),
    ]
