# Generated by Django 5.2.8 on 2025-12-07 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('groq', 'Groq'), ('huggingface', 'HuggingFace'), ('openrouter', 'OpenRouter'), ('cohere', 'Cohere'), ('deepinfra', 'DeepInfra')], db_index=True, max_length=20)),
                ('api_key_encrypted', models.TextField(help_text='Fernet-encrypted API key')),
                ('key_nickname', models.CharField(blank=True, help_text='User-friendly name for this key', max_length=100)),
                ('daily_quota', models.IntegerField(default=1000, help_text='Max requests per day')),
                ('minute_quota', models.IntegerField(default=15, help_text='Max requests per minute')),
                ('requests_today', models.IntegerField(default=0)),
                ('requests_this_month', models.IntegerField(default=0)),
                ('requests_last_minute', models.IntegerField(default=0)),
                ('avg_latency_ms', models.IntegerField(default=500)),
                ('error_count_last_hour', models.IntegerField(default=0)),
                ('health_score', models.IntegerField(default=100, help_text='0-100, higher is healthier')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User API Key',
                'verbose_name_plural': 'User API Keys',
                'ordering': ['-health_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('quota_exceeded', 'Quota Exceeded'), ('timeout', 'Timeout'), ('rate_limited', 'Rate Limited')], db_index=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('cached', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
                ('key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='ai_gateway.userapikey')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('provider', models.CharField(db_index=True, max_length=20)),
                ('requests_count', models.IntegerField(default=0)),
                ('tokens_total', models.IntegerField(default=0)),
                ('avg_latency', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=100.0)),
                ('error_count', models.IntegerField(default=0)),
                ('cache_hit_count', models.IntegerField(default=0)),
                ('estimated_cost_saved', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_daily_analytics', to=settings.AUTH_USER_MODEL)),
                ('key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_analytics', to='ai_gateway.userapikey')),
            ],
            options={
                'verbose_name': 'Daily Analytics',
                'verbose_name_plural': 'Daily Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='userapikey',
            index=models.Index(fields=['user', 'provider', 'is_active'], name='ai_gateway__user_id_e70ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='userapikey',
            index=models.Index(fields=['user', 'is_active', '-health_score'], name='ai_gateway__user_id_5271c5_idx'),
        ),
        migrations.AddIndex(
            model_name='userapikey',
            index=models.Index(fields=['provider', 'is_active'], name='ai_gateway__provide_62c401_idx'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['user', 'timestamp'], name='ai_gateway__user_id_470f02_idx'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['provider', 'timestamp'], name='ai_gateway__provide_c105a6_idx'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['key', 'timestamp'], name='ai_gateway__key_id_80c917_idx'),
        ),
        migrations.AddIndex(
            model_name='usagelog',
            index=models.Index(fields=['status', 'timestamp'], name='ai_gateway__status_7e5787_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyanalytics',
            index=models.Index(fields=['user', 'date'], name='ai_gateway__user_id_24383e_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyanalytics',
            index=models.Index(fields=['provider', 'date'], name='ai_gateway__provide_fc45cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyanalytics',
            unique_together={('date', 'key')},
        ),
    ]
