# Generated by Django 5.2.8 on 2025-12-07 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_gateway', '0001_initial_ai_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyModelUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('daily_quota', models.IntegerField(default=1500)),
                ('minute_quota', models.IntegerField(default=15)),
                ('requests_today', models.IntegerField(default=0)),
                ('requests_last_minute', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_usages', to='ai_gateway.userapikey')),
            ],
            options={
                'indexes': [models.Index(fields=['key', 'model'], name='ai_gateway__key_id_33fc92_idx')],
                'unique_together': {('key', 'model')},
            },
        ),
    ]
