# Generated by Django 5.2.8 on 2025-12-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_gateway', '0002_keymodelusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='tokens_used_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userapikey',
            name='tokens_used_today',
            field=models.IntegerField(default=0),
        ),
    ]
