# Generated by Django 5.2.8 on 2025-12-10 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_gateway', '0003_userapikey_tokens_used_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openrouter', 'OpenRouter'), ('groq', 'Groq'), ('huggingface', 'HuggingFace'), ('cohere', 'Cohere'), ('deepinfra', 'DeepInfra'), ('pollinations', 'Pollinations')], db_index=True, max_length=30)),
                ('model_id', models.CharField(db_index=True, help_text='e.g. gemini-2.0-flash', max_length=100)),
                ('display_name', models.CharField(help_text='Human-readable name', max_length=150)),
                ('is_text', models.BooleanField(default=True, help_text='Can generate text')),
                ('is_image', models.BooleanField(default=False, help_text='Can generate images')),
                ('supports_json_mode', models.BooleanField(default=False)),
                ('supports_function_calling', models.BooleanField(default=False)),
                ('supports_vision', models.BooleanField(default=False, help_text='Can analyze images')),
                ('context_window', models.IntegerField(default=8192, help_text='Max input tokens')),
                ('max_output_tokens', models.IntegerField(default=2048, help_text='Max output tokens')),
                ('default_daily_quota', models.IntegerField(default=1000)),
                ('default_minute_quota', models.IntegerField(default=15)),
                ('default_tokens_per_minute', models.IntegerField(default=100000)),
                ('typical_latency_ms', models.IntegerField(default=500)),
                ('cost_per_1k_input_tokens', models.DecimalField(decimal_places=6, default=0, help_text='Cost in USD per 1K input tokens', max_digits=10)),
                ('cost_per_1k_output_tokens', models.DecimalField(decimal_places=6, default=0, help_text='Cost in USD per 1K output tokens', max_digits=10)),
                ('quality_tier', models.CharField(choices=[('low', 'Low - Fast, cheap'), ('medium', 'Medium - Balanced'), ('high', 'High - Quality focused'), ('premium', 'Premium - Best available')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_free', models.BooleanField(default=False, help_text='No cost to use')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Model Definition',
                'verbose_name_plural': 'Model Definitions',
                'ordering': ['provider', 'model_id'],
                'indexes': [models.Index(fields=['provider', 'is_active'], name='ai_gateway__provide_9351a5_idx'), models.Index(fields=['is_text', 'is_active'], name='ai_gateway__is_text_5b3d26_idx'), models.Index(fields=['is_image', 'is_active'], name='ai_gateway__is_imag_9772ee_idx')],
                'unique_together': {('provider', 'model_id')},
            },
        ),
        migrations.CreateModel(
            name='ModelInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_quota', models.IntegerField(default=1000, help_text='Max requests per day')),
                ('remaining_daily', models.IntegerField(default=1000, help_text='Remaining today')),
                ('minute_quota', models.IntegerField(default=15, help_text='Max requests per minute')),
                ('remaining_minute', models.IntegerField(default=15, help_text='Remaining this minute')),
                ('tokens_per_minute', models.IntegerField(default=100000)),
                ('remaining_tokens_minute', models.IntegerField(default=100000)),
                ('health_score', models.IntegerField(default=100, help_text='Overall health 0-100, based on recent performance')),
                ('availability_score', models.IntegerField(default=100, help_text='Availability 0-100, based on quota and blocks')),
                ('confidence_score', models.FloatField(default=1.0, help_text='Probability (0-1) this model will succeed on next request')),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_reason', models.CharField(blank=True, choices=[('', 'None'), ('QUOTA_EXCEEDED', 'Daily quota exceeded'), ('RATE_LIMITED', 'Rate limit hit'), ('INVALID_KEY', 'API key invalid'), ('MODEL_NOT_FOUND', 'Model not available'), ('CONTENT_FILTER', 'Content blocked'), ('TIMEOUT', 'Request timed out'), ('SERVER_ERROR', 'Provider server error'), ('UNKNOWN', 'Unknown error')], default='', max_length=50)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(db_index=True, default=False)),
                ('block_until', models.DateTimeField(blank=True, null=True)),
                ('block_reason', models.CharField(blank=True, max_length=200)),
                ('total_requests', models.IntegerField(default=0)),
                ('total_successes', models.IntegerField(default=0)),
                ('total_failures', models.IntegerField(default=0)),
                ('avg_latency_ms', models.IntegerField(default=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_instances', to='ai_gateway.userapikey')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='ai_gateway.modeldefinition')),
            ],
            options={
                'verbose_name': 'Model Instance',
                'verbose_name_plural': 'Model Instances',
                'ordering': ['-confidence_score', '-health_score'],
            },
        ),
        migrations.CreateModel(
            name='FailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(db_index=True, max_length=50)),
                ('error_code', models.CharField(blank=True, help_text='HTTP status or error code', max_length=20)),
                ('error_message', models.TextField()),
                ('request_type', models.CharField(default='text', help_text='text or image', max_length=20)),
                ('tokens_attempted', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0, help_text='Time until failure')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_logs', to='ai_gateway.modelinstance')),
            ],
            options={
                'verbose_name': 'Failure Log',
                'verbose_name_plural': 'Failure Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='modelinstance',
            index=models.Index(fields=['api_key', 'is_blocked', '-confidence_score'], name='ai_gateway__api_key_dc467f_idx'),
        ),
        migrations.AddIndex(
            model_name='modelinstance',
            index=models.Index(fields=['model', 'is_blocked', '-confidence_score'], name='ai_gateway__model_i_fed3f9_idx'),
        ),
        migrations.AddIndex(
            model_name='modelinstance',
            index=models.Index(fields=['is_blocked', 'block_until'], name='ai_gateway__is_bloc_beba9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modelinstance',
            unique_together={('api_key', 'model')},
        ),
        migrations.AddIndex(
            model_name='failurelog',
            index=models.Index(fields=['model_instance', 'timestamp'], name='ai_gateway__model_i_141907_idx'),
        ),
        migrations.AddIndex(
            model_name='failurelog',
            index=models.Index(fields=['error_type', 'timestamp'], name='ai_gateway__error_t_0fa3bc_idx'),
        ),
    ]
