# Generated by Django 5.2.8 on 2025-12-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_gateway', '0004_add_model_centric_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldefinition',
            name='quota_reset_hour',
            field=models.IntegerField(default=0, help_text="Hour (0-23 UTC) when daily quota resets. Only used for 'fixed' type."),
        ),
        migrations.AddField(
            model_name='modeldefinition',
            name='quota_reset_type',
            field=models.CharField(choices=[('fixed', 'Fixed time (e.g., midnight UTC)'), ('rolling', 'Rolling window (last 24 hours)'), ('first_use', 'Resets 24h after first use each day')], default='fixed', help_text='How this provider resets quotas', max_length=20),
        ),
    ]
